#
# This Makefile was automatically generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
functions.f90 \
main.f90 \
euler.f90 \
constants.f90

OBJS_f90d1 = \
functions.o \
main.o \
euler.o \
constants.o

SRC_DIR_f90d1 =
OBJS_DIR = ../../../tmp/EulerFTN/obj/
EXE_DIR = /tmp/EulerFTN/

EXE = EulerFTN
FC = gfortran
IDIR =
CFLAGS = -std=f2008 -Wextra -Wall -O2  -march=native  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s
LIBS =

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1))

all : $(EXE)

$(EXE) : $(OBJS_f90d1)
	@mkdir -p $(EXE_DIR)
	$(FC) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
functions.o: \
    functions.f90 \
    constants.o
main.o: \
    main.f90 \
    euler.o
euler.o: \
    euler.f90 \
    functions.o
constants.o: \
    constants.f90

